package entities;

public enum Permission {
	MANAGE_CUSTOMERS,
	MANAGE_RESELLERS,
	MANAGE_PROVIDERS,
	MANAGE_ROLES,
	MANAGE_USERS,
	MANAGE_LIBRARIES,
	MANAGE_CLOUD_LIBRARIES,
	MANAGE_DATACENTERS,
	MANAGE_TAPE_LIBRARIES,
	MANAGE_TASKS,
	MANAGE_EVENTS,
	MANAGE_DOMAIN_ENGINES,
	VIEW_CUSTOMERS,
	VIEW_RESELLERS,
	VIEW_PROVIDERS,
	VIEW_ROLES,
	VIEW_USERS,
	VIEW_LIBRARIES, 
	VIEW_SITES,
	VIEW_CLOUD_LIBRARIES,
	VIEW_DATACENTERS,
	VIEW_TAPE_LIBRARIES,
	VIEW_TASKS,
	VIEW_EVENTS,
	VIEW_DOMAIN_ENGINES;
}
