package entities;

public enum Permission {
	MANAGE_CUSTOMERS,
	MANAGE_RESELLERS,
	MANAGE_PROVIDERS,
	MANAGE_ROLES,
	MANAGE_USERS,
	MANAGE_LIBRARIES,
	MANAGE_CLOUD_LIBRARIES,
	MANAGE_DATACENTERS,
	VIEW_CUSTOMERS,
	VIEW_RESELLERS,
	VIEW_PROVIDERS,
	VIEW_ROLES,
	VIEW_USERS,
	VIEW_LIBRARIES, 
	VIEW_SITES,
	VIEW_CLOUD_LIBRARIES,
	VIEW_DATACENTERS;
}
